version: "3"
services:
  jenkins:
    container_name: jenkins-dood
    build:
      context: .
    image: jenkins-dood:latest
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
      - 50000:50000
    restart: on-failure

volumes:
  jenkins-data:
    name: jenkins-data